# Generated by Django 3.1.2 on 2020-11-07 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0004_auto_20201107_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='view_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
