# Generated by Django 3.1.2 on 2020-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0005_label_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='view_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
