# Generated by Django 3.1.2 on 2020-11-08 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DWHLegator', '0007_auto_20201108_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='osuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
