# Generated by Django 3.1.2 on 2020-11-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0008_entity_osuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='strg_period_type',
            field=models.CharField(blank=True, choices=[('M', 'Months'), ('D', 'Days')], max_length=1, null=True),
        ),
    ]
