# Generated by Django 3.1.2 on 2020-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0011_auto_20201109_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqllist',
            old_name='model_name',
            new_name='sql_name',
        ),
        migrations.AddField(
            model_name='sqllist',
            name='checkin_sql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
