# Generated by Django 3.1.2 on 2020-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0012_auto_20201109_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
