# Generated by Django 3.1.2 on 2020-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0013_group_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='checkout_user',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
    ]
