# Generated by Django 3.1.2 on 2020-11-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DWHLegator', '0016_auto_20201115_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllist',
            name='osuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
