# Generated by Django 3.1.2 on 2020-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0019_auto_20201116_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='archive_flg',
            field=models.SmallIntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=1),
        ),
    ]
