# Generated by Django 3.1.2 on 2021-01-07 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DWHLegator', '0020_auto_20201116_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='checkout_user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='osuser',
        ),
        migrations.AddField(
            model_name='group',
            name='checked_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='checked_out_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Взята на изменение пользователем:'),
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Создана пользователем:'),
        ),
        migrations.AddField(
            model_name='group',
            name='model_name',
            field=models.CharField(max_length=4000, null=True, verbose_name='Имя модели:'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 7, 13, 36, 534546, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменена пользователем:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='anlt_flg',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Хранит значения аналитики:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалена:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Наименование:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fct_table_name',
            field=models.CharField(max_length=256, verbose_name='Таблица хранения по датам:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hist_table_name',
            field=models.CharField(max_length=256, verbose_name='Таблица хранения периодами:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='osuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ОС:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='DWHLegator.entity', verbose_name='Родитель:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tmp_table_name',
            field=models.CharField(max_length=256, verbose_name='Временная таблица (используется при массовых расчетах):'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалена:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='archive_flg',
            field=models.SmallIntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=1, verbose_name='Архивный:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='condition',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. условия для запуска расчета:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='data_type',
            field=models.CharField(choices=[('Число', 'Число'), ('Дата', 'Дата'), ('Строка', 'Строка')], default='Строка', max_length=30, verbose_name='Тип данных:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='deleted',
            field=models.SmallIntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удален:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DWHLegator.entity', verbose_name='Сущность:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='hist_flg',
            field=models.SmallIntegerField(choices=[(0, 'По датам'), (1, 'Периодами')], default=1, verbose_name='Способ хранения:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='mass_sql',
            field=models.TextField(blank=True, null=True, verbose_name='SQL для массового расчета:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='osuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ОС:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_descr',
            field=models.CharField(max_length=256, verbose_name='Описание показателя:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_name',
            field=models.CharField(max_length=256, verbose_name='Наименование показателя:'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_sql',
            field=models.TextField(blank=True, null=True, verbose_name='SQL для расчета за дату:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='checkin_sql',
            field=models.TextField(blank=True, null=True, verbose_name='CHECKIN - запрос:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='checkout_sql',
            field=models.TextField(blank=True, null=True, verbose_name='CHECKOUT - запрос:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='checkout_sql_all',
            field=models.TextField(blank=True, null=True, verbose_name='IMPORT - запрос:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='osuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ОС:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='sql_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Наименование:'),
        ),
    ]
