# Generated by Django 3.1.2 on 2021-01-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0022_auto_20210107_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='checkout_user',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='osuser',
        ),
        migrations.RemoveField(
            model_name='label',
            name='osuser',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='checkout_user',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='osuser',
        ),
        migrations.RemoveField(
            model_name='sqllist',
            name='osuser',
        ),
    ]
