# Generated by Django 3.1.2 on 2021-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0024_auto_20210107_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='modified_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Изменена пользователем:'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modified_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Изменена пользователем:'),
        ),
    ]
