# Generated by Django 3.1.2 on 2021-01-07 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0025_auto_20210107_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllist',
            name='checked_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='checked_out_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Взята на изменение пользователем:'),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='created_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Создана пользователем:'),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалена:'),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='modified_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Изменена пользователем:'),
        ),
    ]
