# Generated by Django 3.1.2 on 2021-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0026_auto_20210107_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='strg_period_type',
            field=models.CharField(blank=True, choices=[('M', 'Месяцев'), ('D', 'Дней')], max_length=1, null=True),
        ),
    ]
