# Generated by Django 3.1.2 on 2021-01-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0028_auto_20210108_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:'),
        ),
        migrations.AlterField(
            model_name='sqllist',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:'),
        ),
    ]
