# Generated by Django 3.1.2 on 2021-01-08 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0029_auto_20210108_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='checked_out',
            field=models.DateTimeField(null=True, verbose_name='Дата и время взятия на изменение:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='checked_out_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Взято на изменение пользователем:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Дата и время создания:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='created_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Создано пользователем:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата и время изменения:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='modified_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Изменено пользователем:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='anlt_flg',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Аналитика:'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tmp_table_name',
            field=models.CharField(max_length=256, verbose_name='Временная таблица:'),
        ),
    ]
