# Generated by Django 3.1.2 on 2021-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0030_auto_20210108_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='err_txt',
            field=models.CharField(max_length=4000, null=True, verbose_name='Текст ошибки:'),
        ),
        migrations.AddField(
            model_name='group',
            name='err_txt',
            field=models.CharField(max_length=4000, null=True, verbose_name='Текст ошибки:'),
        ),
        migrations.AddField(
            model_name='sign',
            name='err_txt',
            field=models.CharField(max_length=4000, null=True, verbose_name='Текст ошибки:'),
        ),
        migrations.AddField(
            model_name='sqllist',
            name='err_txt',
            field=models.CharField(max_length=4000, null=True, verbose_name='Текст ошибки:'),
        ),
    ]
