# Generated by Django 3.1.2 on 2021-01-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0031_auto_20210108_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='err_txt',
        ),
        migrations.RemoveField(
            model_name='group',
            name='err_txt',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='err_txt',
        ),
        migrations.RemoveField(
            model_name='sqllist',
            name='err_txt',
        ),
    ]
