# Generated by Django 3.1.2 on 2021-01-08 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0032_auto_20210108_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analitic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True, verbose_name='Дата и время создания:')),
                ('created_by', models.CharField(max_length=256, null=True, verbose_name='Создано пользователем:')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата и время изменения:')),
                ('modified_by', models.CharField(max_length=256, null=True, verbose_name='Изменено пользователем:')),
                ('checked_out', models.DateTimeField(null=True, verbose_name='Дата и время взятия на изменение:')),
                ('checked_out_by', models.CharField(max_length=256, null=True, verbose_name='Взято на изменение пользователем:')),
                ('deleted', models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:')),
                ('effective_start', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата начала:')),
                ('effective_end', models.DateTimeField(default='31.12.5999 23:59:59', null=True, verbose_name='Дата окончания:')),
                ('anlt_code', models.CharField(max_length=256, null=True, verbose_name='Код:')),
                ('anlt_name', models.CharField(max_length=4000, null=True, verbose_name='Наименование:')),
                ('archive_flg', models.SmallIntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=1, verbose_name='Архивная:')),
                ('anlt_sql', models.TextField(blank=True, null=True, verbose_name='SQL для раскраски фактов:')),
                ('anlt_alias', models.CharField(max_length=30, null=True, verbose_name='Альяс:')),
                ('data_type', models.CharField(choices=[('Число', 'Число'), ('Дата', 'Дата'), ('Строка', 'Строка')], default='Строка', max_length=30, verbose_name='Тип данных:')),
                ('anlt_alias_descr', models.CharField(max_length=1000, null=True, verbose_name='Описание альяса:')),
                ('spec_import_sql', models.TextField(blank=True, null=True, verbose_name='SQL для импорта спецификации:')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DWHLegator.entity', verbose_name='Сущность:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
