# Generated by Django 3.1.2 on 2021-01-09 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DWHLegator', '0033_analitic'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='checked_out',
            field=models.DateTimeField(null=True, verbose_name='Дата и время взятия на изменение:'),
        ),
        migrations.AddField(
            model_name='label',
            name='checked_out_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Взято на изменение пользователем:'),
        ),
        migrations.AddField(
            model_name='label',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Дата и время создания:'),
        ),
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Создано пользователем:'),
        ),
        migrations.AddField(
            model_name='label',
            name='deleted',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Удалено:'),
        ),
        migrations.AddField(
            model_name='label',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата и время изменения:'),
        ),
        migrations.AddField(
            model_name='label',
            name='modified_by',
            field=models.CharField(max_length=256, null=True, verbose_name='Изменено пользователем:'),
        ),
        migrations.AlterField(
            model_name='label',
            name='caption',
            field=models.CharField(max_length=256, unique=True, verbose_name='Наименование:'),
        ),
        migrations.AlterField(
            model_name='label',
            name='ord',
            field=models.IntegerField(verbose_name='Номер по порядку:'),
        ),
        migrations.AlterField(
            model_name='label',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='DWHLegator.label', verbose_name='Родитель:'),
        ),
        migrations.AlterField(
            model_name='label',
            name='view_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL:'),
        ),
    ]
